SELECT 
    TABLE_SCHEMA as siteDatabase,
    TABLE_NAME as sitetable,
    CASE 
        WHEN INDEX_NAME = 'PRIMARY' THEN 'Yes'
        ELSE 'No'
    END as ClusteredIndex,
    GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) as ClusteredColumns,
    'No' as Com_clustedInd,
    TABLE_ROWS
FROM 
    INFORMATION_SCHEMA.STATISTICS s
JOIN 
    INFORMATION_SCHEMA.TABLES t ON s.TABLE_SCHEMA = t.TABLE_SCHEMA AND s.TABLE_NAME = t.TABLE_NAME
WHERE 
    s.TABLE_SCHEMA = %s
    AND INDEX_NAME = 'PRIMARY'
GROUP BY 
    s.TABLE_SCHEMA, s.TABLE_NAME, s.INDEX_NAME, t.TABLE_ROWS
ORDER BY 
    s.TABLE_NAME; 